# Generated by Django 4.1.3 on 2023-01-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_documental_comentario_documental_episodios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='anio',
        ),
        migrations.AddField(
            model_name='documental',
            name='estreno',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='documental',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='estreno',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos'),
        ),
        migrations.AddField(
            model_name='serie',
            name='estreno',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos'),
        ),
    ]
