# Generated by Django 4.1.3 on 2023-01-19 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_remove_pelicula_anio_documental_estreno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documental',
            name='episodios',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='actor_principal',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='actor_principal',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='temporadas',
        ),
        migrations.AddField(
            model_name='documental',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serie',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
